Fix typescript error
I was getting the error

```
packages/client/src/utils.ts:49:8 - error TS2322: Type 'T' is not assignable to type 'object
```

Perhaps this is surfacing due to an updated version?
That or it's the node version on my local machine